-- =============================================
-- V2: Seed platform admin account
-- =============================================

-- Platform system tenant (reserved, not a real business tenant)
INSERT INTO t_tenant (name, status, plan_type, contact_email)
SELECT 'Lazyday Platform', 'ACTIVE', 'ENTERPRISE', 'admin@lazyday.com'
WHERE NOT EXISTS (SELECT 1 FROM t_tenant WHERE name = 'Lazyday Platform');

-- Platform admin user
-- Password: Admin1234! (BCrypt hash, generated by htpasswd -nbBC 10)
-- Role: PLATFORM_ADMIN (full system access)
INSERT INTO t_user (name, username, email, password_hash, role, status, tenant_id)
SELECT 'Platform Admin', 'admin', 'admin@lazyday.com',
       '$2y$10$N3tKj3fVeg2GmqcMq/nkzez.mVNvbFYazrrrz3dpJwgEwsJvsByTO',
       'PLATFORM_ADMIN', 'ACTIVE', t.id
FROM t_tenant t
WHERE t.name = 'Lazyday Platform'
  AND NOT EXISTS (SELECT 1 FROM t_user WHERE username = 'admin');
